import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { connectToDatabase } from "../util/mongodb";
import { InferGetServerSidePropsType } from "next";
import Login from "./login";
import Logo from "../util/logo";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  isConnected,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Noted</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.logo}>
          <Logo />
        </div>
        {!isConnected && (
          <div className={styles.connect}>
            There was an issue connecting to the Mongo Database. No connection
            made
          </div>
        )}
        <div className={styles.login}>
          <Login />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { db } = await connectToDatabase();

  if (db) {
    return {
      props: {
        isConnected: true,
      },
    };
  }
  return {
    props: {
      isConnected: false,
    },
  };
}
